# Site settings
title: "HaskellBR Blog"
logo: logo.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: tacla.yamada@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  O Blog da HaskellBR é um blog em português aberto para contribuições sobre a
  linguagem de programação Haskell.
url: "http://localhost:4000/" # the base hostname & protocol for your site
baseurl: /blog # the subpath of your site, e.g. /blog/
# twitter_username: haskellbr
github_username:  haskellbr

# Build settings
markdown: kramdown
